### ISSUE TITLE
Missing Registrar's response

### ISSUE THREAD

**Issue by jameswang2015** [openrdap/rdap#10]
It appears to me that this openrdap only uses registry's response but the registrar's response, which typically provides more info (so called thick lookup), are missing. For example, if we rdap lookup google.com, the response don't have google location information which is only available from registrar's server. 

I also tried -s url/of/registrar, for example `rdap -s https://rdap.markmonitor.com/rdap google.com` but get 404 error.

Can you add the support of registrar's server url?

**Comment by skip2** [comment]
I've fixed queries to markmonitor's rdap server in https://github.com/openrdap/rdap/commit/abc42c194094bc23766f292e90d51d4969ef4945.

The query `rdap -s https://rdap.markmonitor.com/rdap google.com` should work now.

https://www.openrdap.org/demo?cmd=rdap+-s+https%3A%2F%2Frdap.markmonitor.com%2Frdap+google.com

**Comment by jameswang2015** [comment]
Great!

**Comment by jameswang2015** [comment]
I rerun `go get -u github.com/openrdap/rdap/cmd/rdap` and updated rdap, but when run `rdap -s https://rdap.markmonitor.com/rdap google.com` at my terminal I still get error.
```
# Error: No RDAP servers responded successfully (tried 1 server(s))
```
can you create a new release and make the `go get - u ...` work? or let me know if I do something wrong. Thanks

**Comment by jameswang2015** [comment]
as a follow-up question, I noticed that the current tool can only make one query of either bootstrap server (by default) or other registrar's server (by using -s for custom url). Can the tool be made to automatically query both bootstrap and then registrar's server and provide both responses?
